#!/bin/sh

# Make sure natural scrolling is always turned on for the trackpad
xinput --set-prop "SYNA8005:00 06CB:CD8C Touchpad" "libinput Natural Scrolling Enabled" 1

# Configure xrdb to look in XDG directory for Xresources
xrdb -merge ~/.config/x11/Xresources

# Turn off bell sound
xset -b

# Set the Windows key to be my compose key for things like ë
setxkbmap -option compose:lwin

# Setup sxhkd (simple x hotkey daemon)
pgrep -x sxhkd > /dev/null || sxhkd &

# Change default cursor to arrow shape
xsetroot -cursor_name left_ptr

# Notify autorandr of screen change because of startup
autorandr --change

# Setup default UI elements like Pywal, polybar and dunst
setup-ui

exec bspwm
