#! /bin/sh

bspc monitor eDP1 -d I II III IV V 
bspc monitor HDMI1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Dunst layer='above'
bspc rule -a Zathura state=tiled
