#! /bin/sh
intern=eDP1
extern=HDMI1

if xrandr | grep "$extern disconnected"; then
	bspc monitor $intern -d I II III IV V VI VII VIII IX X
else
	bspc monitor $extern -d I II III IV V 
	bspc monitor $intern -d VI VII VIII IX X
fi

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding          0
bspc config bottom_padding       0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Dunst layer='above'
bspc rule -a Zathura state=tiled
